# This file was generated by pydantic2django
# Do not edit this file manually
# Generated on 2025-03-13 09:50:45


# Constants for default values
true = True
false = False


# Define a proper undefined type that won't cause issues with Django
class UndefinedType:
    def __repr__(self):
        return "Undefined"

    def __bool__(self):
        return False


PydanticUndefined = UndefinedType()

# Additional imports


__all__ = []
