site_name: Pydantic2Django
site_description: Convert Pydantic models to Django models dynamically

# When publishing to GitHub Pages, this will be set by the action
# site_url can be added later if desired

theme:
  name: material

docs_dir: docs

plugins:
  - search
  - awesome-nav
  - api-autonav:
      modules:
        - pydantic2django

markdown_extensions:
  - admonition
  - def_list
  - tables
  - footnotes
  - toc:
      permalink: true

# Navigation is provided via docs/.nav.yml (Awesome Nav)
